import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Creates the `users` table for the Authentication bounded context.
 *
 * This migration is the first in the dependency chain (B-A01-T1) and must
 * be executed before any other authentication-related migration or seed.
 *
 * Key design decisions:
 * - UUID v4 primary key generated by PostgreSQL (`gen_random_uuid()`).
 * - `user_role` PostgreSQL enum for type safety at the database level.
 * - Partial unique index on `email` restricted to active users
 *   (`WHERE deleted_at IS NULL`), allowing email reuse after soft deletion.
 * - `timestamptz` for all temporal columns to ensure timezone awareness.
 */
export class CreateUsersTable1714000000000 implements MigrationInterface {
  name = 'CreateUsersTable1714000000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // Create the user_role enum type
    await queryRunner.query(`
      DO $$
      BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role') THEN
          CREATE TYPE "user_role" AS ENUM ('registered', 'guest');
        END IF;
      END
      $$;
    `);

    // Create the users table
    await queryRunner.query(`
        CREATE TABLE IF NOT EXISTS "users"
        (
            "id"
            UUID
            NOT
            NULL
            DEFAULT
            gen_random_uuid
        (
        ),
            "email" VARCHAR
        (
            255
        ) NOT NULL,
            "password_hash" VARCHAR
        (
            255
        ) NOT NULL,
            "username" VARCHAR
        (
            50
        ) NOT NULL,
            "role" "user_role" NOT NULL DEFAULT 'registered',
            "refresh_token_hash" VARCHAR
        (
            255
        ) DEFAULT NULL,
            "created_at" TIMESTAMPTZ NOT NULL DEFAULT now
        (
        ),
            "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now
        (
        ),
            "deleted_at" TIMESTAMPTZ DEFAULT NULL,
            CONSTRAINT "PK_users" PRIMARY KEY
        (
            "id"
        )
            );
    `);

    // Partial unique index: email uniqueness among active users only
    await queryRunner.query(`
        CREATE UNIQUE INDEX IF NOT EXISTS "IDX_users_email_active"
            ON "users" ("email")
            WHERE "deleted_at" IS NULL;
    `);

    // Performance index on deleted_at for soft-delete filtering
    await queryRunner.query(`
        CREATE INDEX IF NOT EXISTS "IDX_users_deleted_at"
            ON "users" ("deleted_at");
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE IF EXISTS "users";`);
    await queryRunner.query(`DROP TYPE IF EXISTS "user_role";`);
  }
}
