import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Creates the `rooms` and `room_memberships` tables for the Room bounded
 * context.
 *
 * This migration is the first in the dependency chain for Sprint 2
 * and must be executed before any other Room-related migration,
 * service, or controller. Both tables hold a foreign key to `users`, so
 * `CreateUsersTable1714000000000` must have run first.
 *
 * Key design decisions:
 * - UUID v4 primary keys generated by PostgreSQL (`gen_random_uuid()`),
 *   consistent with the `users` table.
 * - `rooms.deleted_at` implements soft deletion so historical
 *   `room_memberships` rows remain valid for audit purposes, per the Data
 *   Model Specification §2.1.2.
 * - `room_memberships` uses a **partial** unique index on
 *   (`room_id`, `user_id`) restricted to `WHERE left_at IS NULL`, rather
 *   than a hard unique constraint on the pair. This allows a user to leave
 *   and later rejoin the same room (a new row with `left_at = NULL`),
 *   while still preventing two simultaneous active memberships — matching
 *   the join endpoint's documented behaviour (409 on duplicate *active*
 *   membership, not on historical reuse).
 * - `timestamptz` for all temporal columns, consistent with the
 *   Authentication migration.
 */
export class CreateRoomsTable1784015715536 implements MigrationInterface {
  name = 'CreateRoomsTable1784015715536';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "rooms" (
        "id" UUID NOT NULL DEFAULT gen_random_uuid(),
        "name" VARCHAR(100) NOT NULL,
        "description" TEXT DEFAULT NULL,
        "owner_id" UUID NOT NULL,
        "is_public" BOOLEAN NOT NULL DEFAULT true,
        "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
        "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
        "deleted_at" TIMESTAMPTZ DEFAULT NULL,
        CONSTRAINT "PK_rooms" PRIMARY KEY ("id"),
        CONSTRAINT "FK_rooms_owner_id" FOREIGN KEY ("owner_id")
          REFERENCES "users" ("id") ON DELETE RESTRICT
      );
    `);

    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "IDX_rooms_owner_id"
        ON "rooms" ("owner_id");
    `);

    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "IDX_rooms_deleted_at"
        ON "rooms" ("deleted_at");
    `);

    // Speeds up the public listing query (GET /rooms: is_public = true AND
    // deleted_at IS NULL), which is expected to be the hottest read path
    // for this bounded context.
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "IDX_rooms_public_active"
        ON "rooms" ("is_public")
        WHERE "deleted_at" IS NULL;
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "room_memberships" (
        "id" UUID NOT NULL DEFAULT gen_random_uuid(),
        "room_id" UUID NOT NULL,
        "user_id" UUID NOT NULL,
        "joined_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
        "left_at" TIMESTAMPTZ DEFAULT NULL,
        CONSTRAINT "PK_room_memberships" PRIMARY KEY ("id"),
        CONSTRAINT "FK_room_memberships_room_id" FOREIGN KEY ("room_id")
          REFERENCES "rooms" ("id") ON DELETE CASCADE,
        CONSTRAINT "FK_room_memberships_user_id" FOREIGN KEY ("user_id")
          REFERENCES "users" ("id") ON DELETE RESTRICT
      );
    `);

    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "IDX_room_memberships_room_id"
        ON "room_memberships" ("room_id");
    `);

    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "IDX_room_memberships_user_id"
        ON "room_memberships" ("user_id");
    `);

    // Partial unique index: a user may hold at most one *active*
    // (left_at IS NULL) membership per room. Historical rows where
    // left_at is set are excluded, permitting rejoin after leave.
    await queryRunner.query(`
      CREATE UNIQUE INDEX IF NOT EXISTS "IDX_room_memberships_active_unique"
        ON "room_memberships" ("room_id", "user_id")
        WHERE "left_at" IS NULL;
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE IF EXISTS "room_memberships";`);
    await queryRunner.query(`DROP TABLE IF EXISTS "rooms";`);
  }
}
